name: Run Tests & Upload Coverage

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Download Battlesnake Linux binary
        run: |
          mkdir -p battlesnake
          curl -L -o battlesnake/battlesnake-linux https://github.com/BattlesnakeHQ/rules/releases/latest/download/battlesnake-linux
          chmod +x battlesnake/battlesnake-linux

      - name: Start server
        run: |
          npm run start:ci &
          npx wait-on http://localhost:8000

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
